// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFebxbZMQXWkMnRh2IhGGbjTn-ACpgTA',
    appId: '1:624320109169:web:b57b966ad31378e1f619d0',
    messagingSenderId: '624320109169',
    projectId: 'acme-institute-7e73a',
    authDomain: 'acme-institute-7e73a.firebaseapp.com',
    storageBucket: 'acme-institute-7e73a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEdEcuHpHIczqGv2h4YPtSPac8jcQ-YyI',
    appId: '1:624320109169:android:4c7c5ac71d384755f619d0',
    messagingSenderId: '624320109169',
    projectId: 'acme-institute-7e73a',
    storageBucket: 'acme-institute-7e73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmhvzdJvUrojyuimh5G6ByJhzJuzr0YM',
    appId: '1:624320109169:ios:e429188c1dc52d77f619d0',
    messagingSenderId: '624320109169',
    projectId: 'acme-institute-7e73a',
    storageBucket: 'acme-institute-7e73a.firebasestorage.app',
    iosBundleId: 'com.example.acmeInstitute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmhvzdJvUrojyuimh5G6ByJhzJuzr0YM',
    appId: '1:624320109169:ios:e429188c1dc52d77f619d0',
    messagingSenderId: '624320109169',
    projectId: 'acme-institute-7e73a',
    storageBucket: 'acme-institute-7e73a.firebasestorage.app',
    iosBundleId: 'com.example.acmeInstitute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgFebxbZMQXWkMnRh2IhGGbjTn-ACpgTA',
    appId: '1:624320109169:web:068cbf67c43bcad9f619d0',
    messagingSenderId: '624320109169',
    projectId: 'acme-institute-7e73a',
    authDomain: 'acme-institute-7e73a.firebaseapp.com',
    storageBucket: 'acme-institute-7e73a.firebasestorage.app',
  );
}
